default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.11
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [python, pyproject]
        args: [--fix, --unsafe-fixes]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter, pyproject]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          [
            --no-strict-optional,
            --ignore-missing-imports,
            --no-namespace-packages,
          ]
        additional_dependencies:
          [
            "pandas-stubs",
            "types-requests",
            "types-pytz",
            "types-python-dateutil",
            "types-beautifulsoup4",
          ]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
